### ISSUE TITLE
Schedule is not generated anymore + Changes in TI/LOG PDF files

### ISSUE THREAD

**Issue by VictorEmmanuelPadel** [Krystosterone/rubik#32]
When selecting courses and clicking on `Soumettre`, the website keeps processing but no schedule is generated.

In addition, ETS just made some changes in the LOG and TI programs yesterday night. PDF files have been updated and might need to be uploaded again into Rubik.

**Comment by Krystosterone** [comment]
I'd need a bit more details on what course combination you are trying out, as logs and my own testing seems to indicate that everything seems to be working fine.

I'll take a look at the new PDFs in the meantime.

**Comment by Krystosterone** [comment]
I cannot reproduce the bug around no schedules generated but I have updated the website to include the new PDFs. Cheers
