### ISSUE TITLE
Listes de cours pas à jour pour l'automne 2019

### ISSUE THREAD

**Issue by alwaysbeshels** [Krystosterone/rubik#33]
L'école a effectué de gros changements de cours et d'horaires qui seront appliqués dès l'automne 2019. Les nouveaux PDFs d'horaires ont été mis à jour sur le site de l'école [(Lien)](https://www.etsmtl.ca/Etudiants/Horaire-cours) pour les programmes concernés. 

Dans la plateforme de Rubik, les horaires ne sont pas à jour et il y manque les nouveaux cours pour les programmes concernés.

**Comment by alwaysbeshels** [comment]
Est-ce que quelqu'un pourrait approuver le pull request pour qu'on ait accès aux nouveaux horaires, svp? 
Could someone approve the pull request so we can access the new schedules, please?

@Krystosterone @xuorig @brianquirion

**Comment by Krystosterone** [comment]
Merci pour le PR!

**Comment by Krystosterone** [comment]
Merci pour votre patience! Les nouveaux horaires sont maintenant déployés!
