### ISSUE TITLE
Erreur dans l'horaire du cours MEC741

### ISSUE THREAD

**Issue by Stephkako** [Krystosterone/rubik#46]
Devrait être lundi et mardi soirs

**Comment by Hyftar** [comment]
L'école a apporté des changements aux horraires il y a de ça 3 jours, la PR #44 apporte ces changements au site. SVP de bien vouloir ne pas ouvrir d'autre Issue pour ce même problème et laisser le temps à @Krystosterone de merge la PR.

**Comment by Stephkako** [comment]
Ok! Désolée et merci!
