### ISSUE TITLE
Erreur dans l'horaire du cours de LOG635

### ISSUE THREAD

**Issue by VBoucher** [Krystosterone/rubik#47]
Bonjour,

Le PDF dit que le cours LOG635 groupe 2 est le Mardi matin et mardi après-midi pour les 2 sous-groupes. Votre site indique que le groupe est le mardi matin et le mardi après-midi pour le sous-groupe 1 mais vendredi après-midi pour le sous-groupe 2

Rubik :
![image](https://user-images.githubusercontent.com/33044970/67638261-da33a780-f8b8-11e9-984c-12d6d72d0797.png)

PDF ÉTS :
![image](https://user-images.githubusercontent.com/33044970/67638278-04856500-f8b9-11e9-8f9c-5b3f7cb736be.png)

**Comment by Hyftar** [comment]
L'université a modifié les horaires voilà maintenant 4 jours, la PR #44 modifie le site avec les nouveaux horaires, on attends juste que @Krystosterone merge le tout.
