### ISSUE TITLE
Distribuer le logiciel sous la licence de logiciel libre

### ISSUE THREAD

**Issue by Krystosterone** [Krystosterone/rubik#8]
> Sinon beau travail! Le site est clean et c'est pratique. Je te suggère de soumettre ton projet à la Maison du Logiciel Libre qui ouvre bientôt, où des étudiants de l'ETS vont apprendre à contribuer à des projets libres. http://maisonlogiciellibre.org/
> 
> Salut Krystian, comme le suggère @samdidos, la maison du logiciel libre est une très belle opportunité! Tu peux créer des missions pour ton projet auxquelles tout le monde peut participer pour bénéficier d'une visibilité tout en contribuant pour la communauté! :smile:

**Comment by JulienRobitaille** [comment]
Salut, j'aimerais te relancer sur la possibilité de distribuer ton logiciel sous une licence plus permissive.
Je te propose celle-ci : https://tldrlegal.com/license/bsd-3-clause-license-(revised)

Je pense que ça assurerait plus la pérennité de ce projet et encouragerait les contributions.

Merci pour ce beau projet !

**Comment by Krystosterone** [comment]
Done! As of b815a1bda0511375826b69d9adcec894510426b6 and ac6620be864f6cf1688e9f8167e2c2eb1f920b7c
